"""
This type stub file was generated by pyright.
"""

from html.parser import HTMLParser
from typing import Any

FRAME = ...
ALL = ...
NONE = ...
HEADER = ...
DEFAULT = ...
MSWORD_FRIENDLY = ...
PLAIN_COLUMNS = ...
MARKDOWN = ...
ORGMODE = ...
DOUBLE_BORDER = ...
SINGLE_BORDER = ...
RANDOM = ...
BASE_ALIGN_VALUE = ...
_re = ...

class PrettyTable:
    def __init__(self, field_names=..., **kwargs) -> None:
        """Return a new PrettyTable instance

        Arguments:

        encoding - Unicode encoding scheme used to decode any encoded input
        title - optional table title
        field_names - list or tuple of field names
        fields - list or tuple of field names to include in displays
        start - index of first data row to include in output
        end - index of last data row to include in output PLUS ONE (list slice style)
        header - print a header showing field names (True or False)
        header_style - stylisation to apply to field names in header
            ("cap", "title", "upper", "lower" or None)
        border - print a border around the table (True or False)
        preserve_internal_border - print a border inside the table even if
            border is disabled (True or False)
        hrules - controls printing of horizontal rules after rows.
            Allowed values: FRAME, HEADER, ALL, NONE
        vrules - controls printing of vertical rules between columns.
            Allowed values: FRAME, ALL, NONE
        int_format - controls formatting of integer data
        float_format - controls formatting of floating point data
        custom_format - controls formatting of any column using callable
        min_table_width - minimum desired table width, in characters
        max_table_width - maximum desired table width, in characters
        min_width - minimum desired field width, in characters
        max_width - maximum desired field width, in characters
        padding_width - number of spaces on either side of column data
            (only used if left and right paddings are None)
        left_padding_width - number of spaces on left hand side of column data
        right_padding_width - number of spaces on right hand side of column data
        vertical_char - single character string used to draw vertical lines
        horizontal_char - single character string used to draw horizontal lines
        horizontal_align_char - single character string used to indicate alignment
        junction_char - single character string used to draw line junctions
        top_junction_char - single character string used to draw top line junctions
        bottom_junction_char -
            single character string used to draw bottom line junctions
        right_junction_char - single character string used to draw right line junctions
        left_junction_char - single character string used to draw left line junctions
        top_right_junction_char -
            single character string used to draw top-right line junctions
        top_left_junction_char -
            single character string used to draw top-left line junctions
        bottom_right_junction_char -
            single character string used to draw bottom-right line junctions
        bottom_left_junction_char -
            single character string used to draw bottom-left line junctions
        sortby - name of field to sort rows by
        sort_key - sorting key function, applied to data points before sorting
        align - default align for each column (None, "l", "c" or "r")
        valign - default valign for each row (None, "t", "m" or "b")
        reversesort - True or False to sort in descending or ascending order
        oldsortslice - Slice rows before sorting in the "old style" """
        ...

    def __getattr__(self, name: str):  # -> int:
        ...
    def __getitem__(self, index):  # -> PrettyTable:
        ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @property
    def rows(self) -> list[Any]: ...
    @property
    def dividers(self) -> list[bool]: ...
    @property
    def xhtml(self) -> bool:
        """Print <br/> tags if True, <br> tags if False"""
        ...

    @xhtml.setter
    def xhtml(self, val) -> None: ...
    @property
    def none_format(self):  # -> dict[None, None]:
        ...
    @none_format.setter
    def none_format(self, val):  # -> None:
        ...
    @property
    def field_names(self):  # -> list[str]:
        """List or tuple of field names

        When setting field_names, if there are already field names the new list
        of field names must be the same length. Columns are renamed and row data
        remains unchanged."""
        ...

    @field_names.setter
    def field_names(self, val) -> None: ...
    @property
    def align(self) -> dict[str, str] | dict[str, Any | dict[Any, Any]]:
        """Controls alignment of fields
        Arguments:

        align - alignment, one of "l", "c", or "r" """
        ...

    @align.setter
    def align(self, val) -> None: ...
    @property
    def valign(self):  # -> dict[Any, Any]:
        """Controls vertical alignment of fields
        Arguments:

        valign - vertical alignment, one of "t", "m", or "b" """
        ...

    @valign.setter
    def valign(self, val) -> None: ...
    @property
    def max_width(self):  # -> dict[Any, Any]:
        """Controls maximum width of fields
        Arguments:

        max_width - maximum width integer"""
        ...

    @max_width.setter
    def max_width(self, val) -> None: ...
    @property
    def min_width(self):  # -> dict[Any, Any]:
        """Controls minimum width of fields
        Arguments:

        min_width - minimum width integer"""
        ...

    @min_width.setter
    def min_width(self, val) -> None: ...
    @property
    def min_table_width(self):  # -> None:
        ...
    @min_table_width.setter
    def min_table_width(self, val) -> None: ...
    @property
    def max_table_width(self):  # -> None:
        ...
    @max_table_width.setter
    def max_table_width(self, val) -> None: ...
    @property
    def fields(self):  # -> None:
        """List or tuple of field names to include in displays"""
        ...

    @fields.setter
    def fields(self, val) -> None: ...
    @property
    def title(self):  # -> str | None:
        """Optional table title

        Arguments:

        title - table title"""
        ...

    @title.setter
    def title(self, val) -> None: ...
    @property
    def start(self):  # -> int:
        """Start index of the range of rows to print

        Arguments:

        start - index of first data row to include in output"""
        ...

    @start.setter
    def start(self, val) -> None: ...
    @property
    def end(self):  # -> None:
        """End index of the range of rows to print

        Arguments:

        end - index of last data row to include in output PLUS ONE (list slice style)"""
        ...

    @end.setter
    def end(self, val) -> None: ...
    @property
    def sortby(self):  # -> None:
        """Name of field by which to sort rows

        Arguments:

        sortby - field name to sort by"""
        ...

    @sortby.setter
    def sortby(self, val) -> None: ...
    @property
    def reversesort(self):  # -> bool:
        """Controls direction of sorting (ascending vs descending)

        Arguments:

        reveresort - set to True to sort by descending order, or False to sort by
            ascending order"""
        ...

    @reversesort.setter
    def reversesort(self, val) -> None: ...
    @property
    def sort_key(self):  # -> Callable[..., Any]:
        """Sorting key function, applied to data points before sorting

        Arguments:

        sort_key - a function which takes one argument and returns something to be
        sorted"""
        ...

    @sort_key.setter
    def sort_key(self, val) -> None: ...
    @property
    def header(self):  # -> bool:
        """Controls printing of table header with field names

        Arguments:

        header - print a header showing field names (True or False)"""
        ...

    @header.setter
    def header(self, val) -> None: ...
    @property
    def header_style(self):  # -> None:
        """Controls stylisation applied to field names in header

        Arguments:

        header_style - stylisation to apply to field names in header
            ("cap", "title", "upper", "lower" or None)"""
        ...

    @header_style.setter
    def header_style(self, val) -> None: ...
    @property
    def border(self):  # -> bool:
        """Controls printing of border around table

        Arguments:

        border - print a border around the table (True or False)"""
        ...

    @border.setter
    def border(self, val) -> None: ...
    @property
    def preserve_internal_border(self):  # -> bool:
        """Controls printing of border inside table

        Arguments:

        preserve_internal_border - print a border inside the table even if
            border is disabled (True or False)"""
        ...

    @preserve_internal_border.setter
    def preserve_internal_border(self, val) -> None: ...
    @property
    def hrules(self):  # -> int | None:
        """Controls printing of horizontal rules after rows

        Arguments:

        hrules - horizontal rules style.  Allowed values: FRAME, ALL, HEADER, NONE"""
        ...

    @hrules.setter
    def hrules(self, val) -> None: ...
    @property
    def vrules(self):  # -> int:
        """Controls printing of vertical rules between columns

        Arguments:

        vrules - vertical rules style.  Allowed values: FRAME, ALL, NONE"""
        ...

    @vrules.setter
    def vrules(self, val) -> None: ...
    @property
    def int_format(self):  # -> dict[Any, Any]:
        """Controls formatting of integer data
        Arguments:

        int_format - integer format string"""
        ...

    @int_format.setter
    def int_format(self, val) -> None: ...
    @property
    def float_format(self):  # -> dict[Any, Any]:
        """Controls formatting of floating point data
        Arguments:

        float_format - floating point format string"""
        ...

    @float_format.setter
    def float_format(self, val) -> None: ...
    @property
    def custom_format(self):  # -> dict[Any, Any]:
        """Controls formatting of any column using callable
        Arguments:

        custom_format - Dictionary of field_name and callable"""
        ...

    @custom_format.setter
    def custom_format(self, val):  # -> None:
        ...
    @property
    def padding_width(self):  # -> int:
        """The number of empty spaces between a column's edge and its content

        Arguments:

        padding_width - number of spaces, must be a positive integer"""
        ...

    @padding_width.setter
    def padding_width(self, val) -> None: ...
    @property
    def left_padding_width(self):  # -> None:
        """The number of empty spaces between a column's left edge and its content

        Arguments:

        left_padding - number of spaces, must be a positive integer"""
        ...

    @left_padding_width.setter
    def left_padding_width(self, val) -> None: ...
    @property
    def right_padding_width(self):  # -> None:
        """The number of empty spaces between a column's right edge and its content

        Arguments:

        right_padding - number of spaces, must be a positive integer"""
        ...

    @right_padding_width.setter
    def right_padding_width(self, val) -> None: ...
    @property
    def vertical_char(self):  # -> str:
        """The character used when printing table borders to draw vertical lines

        Arguments:

        vertical_char - single character string used to draw vertical lines"""
        ...

    @vertical_char.setter
    def vertical_char(self, val) -> None: ...
    @property
    def horizontal_char(self):  # -> str:
        """The character used when printing table borders to draw horizontal lines

        Arguments:

        horizontal_char - single character string used to draw horizontal lines"""
        ...

    @horizontal_char.setter
    def horizontal_char(self, val) -> None: ...
    @property
    def horizontal_align_char(self):  # -> str:
        """The character used to indicate column alignment in horizontal lines

        Arguments:

        horizontal_align_char - single character string used to indicate alignment"""
        ...

    @horizontal_align_char.setter
    def horizontal_align_char(self, val) -> None: ...
    @property
    def junction_char(self):  # -> str:
        """The character used when printing table borders to draw line junctions

        Arguments:

        junction_char - single character string used to draw line junctions"""
        ...

    @junction_char.setter
    def junction_char(self, val) -> None: ...
    @property
    def top_junction_char(self):  # -> str:
        """The character used when printing table borders to draw top line junctions

        Arguments:

        top_junction_char - single character string used to draw top line junctions"""
        ...

    @top_junction_char.setter
    def top_junction_char(self, val) -> None: ...
    @property
    def bottom_junction_char(self):  # -> str:
        """The character used when printing table borders to draw bottom line junctions

        Arguments:

        bottom_junction_char -
            single character string used to draw bottom line junctions"""
        ...

    @bottom_junction_char.setter
    def bottom_junction_char(self, val) -> None: ...
    @property
    def right_junction_char(self):  # -> str:
        """The character used when printing table borders to draw right line junctions

        Arguments:

        right_junction_char -
            single character string used to draw right line junctions"""
        ...

    @right_junction_char.setter
    def right_junction_char(self, val) -> None: ...
    @property
    def left_junction_char(self):  # -> str:
        """The character used when printing table borders to draw left line junctions

        Arguments:

        left_junction_char - single character string used to draw left line junctions"""
        ...

    @left_junction_char.setter
    def left_junction_char(self, val) -> None: ...
    @property
    def top_right_junction_char(self):  # -> str:
        """
        The character used when printing table borders to draw top-right line junctions

        Arguments:

        top_right_junction_char -
            single character string used to draw top-right line junctions"""
        ...

    @top_right_junction_char.setter
    def top_right_junction_char(self, val) -> None: ...
    @property
    def top_left_junction_char(self):  # -> str:
        """
        The character used when printing table borders to draw top-left line junctions

        Arguments:

        top_left_junction_char -
            single character string used to draw top-left line junctions"""
        ...

    @top_left_junction_char.setter
    def top_left_junction_char(self, val) -> None: ...
    @property
    def bottom_right_junction_char(self):  # -> str:
        """The character used when printing table borders
           to draw bottom-right line junctions

        Arguments:

        bottom_right_junction_char -
            single character string used to draw bottom-right line junctions"""
        ...

    @bottom_right_junction_char.setter
    def bottom_right_junction_char(self, val) -> None: ...
    @property
    def bottom_left_junction_char(self):  # -> str:
        """The character used when printing table borders
           to draw bottom-left line junctions

        Arguments:

        bottom_left_junction_char -
            single character string used to draw bottom-left line junctions"""
        ...

    @bottom_left_junction_char.setter
    def bottom_left_junction_char(self, val) -> None: ...
    @property
    def format(self):  # -> bool:
        """Controls whether or not HTML tables are formatted to match styling options

        Arguments:

        format - True or False"""
        ...

    @format.setter
    def format(self, val) -> None: ...
    @property
    def print_empty(self):  # -> bool:
        """Controls whether or not empty tables produce a header and frame or just an
        empty string

        Arguments:

        print_empty - True or False"""
        ...

    @print_empty.setter
    def print_empty(self, val) -> None: ...
    @property
    def attributes(self):  # -> dict[Any, Any]:
        """A dictionary of HTML attribute name/value pairs to be included in the
        <table> tag when printing HTML

        Arguments:

        attributes - dictionary of attributes"""
        ...

    @attributes.setter
    def attributes(self, val) -> None: ...
    @property
    def oldsortslice(self):  # -> bool:
        """oldsortslice - Slice rows before sorting in the "old style" """
        ...

    @oldsortslice.setter
    def oldsortslice(self, val) -> None: ...
    def set_style(self, style) -> None: ...
    def add_rows(self, rows) -> None:
        """Add rows to the table

        Arguments:

        rows - rows of data, should be an iterable of lists, each list with as many
        elements as the table has fields"""
        ...

    def add_row(self, row: list[str]) -> None:
        """Add a row to the table

        Arguments:

        row - row of data, should be a list with as many elements as the table
        has fields"""
        ...

    def del_row(self, row_index) -> None:
        """Delete a row from the table

        Arguments:

        row_index - The index of the row you want to delete.  Indexing starts at 0."""
        ...

    def add_column(
        self, fieldname, column, align: str = ..., valign: str = ...
    ) -> None:
        """Add a column to the table.

        Arguments:

        fieldname - name of the field to contain the new column of data
        column - column of data, should be a list with as many elements as the
        table has rows
        align - desired alignment for this column - "l" for left, "c" for centre and
            "r" for right
        valign - desired vertical alignment for new columns - "t" for top,
            "m" for middle and "b" for bottom"""
        ...

    def add_autoindex(self, fieldname: str = ...) -> None:
        """Add an auto-incrementing index column to the table.
        Arguments:
        fieldname - name of the field to contain the new column of data"""
        ...

    def del_column(self, fieldname) -> None:
        """Delete a column from the table

        Arguments:

        fieldname - The field name of the column you want to delete."""
        ...

    def clear_rows(self) -> None:
        """Delete all rows from the table but keep the current field names"""
        ...

    def clear(self) -> None:
        """Delete all rows and field names from the table, maintaining nothing but
        styling options"""
        ...

    def copy(self):  # -> Self:
        ...
    def get_formatted_string(self, out_format: str = ..., **kwargs) -> str:
        """Return string representation of specified format of table in current state.

        Arguments:
        out_format - resulting table format
        kwargs - passed through to function that performs formatting
        """
        ...

    def get_string(self, **kwargs: Any) -> str:
        """Return string representation of table in current state.

        Arguments:

        title - optional table title
        start - index of first data row to include in output
        end - index of last data row to include in output PLUS ONE (list slice style)
        fields - names of fields (columns) to include
        header - print a header showing field names (True or False)
        border - print a border around the table (True or False)
        preserve_internal_border - print a border inside the table even if
            border is disabled (True or False)
        hrules - controls printing of horizontal rules after rows.
            Allowed values: ALL, FRAME, HEADER, NONE
        vrules - controls printing of vertical rules between columns.
            Allowed values: FRAME, ALL, NONE
        int_format - controls formatting of integer data
        float_format - controls formatting of floating point data
        custom_format - controls formatting of any column using callable
        padding_width - number of spaces on either side of column data (only used if
            left and right paddings are None)
        left_padding_width - number of spaces on left hand side of column data
        right_padding_width - number of spaces on right hand side of column data
        vertical_char - single character string used to draw vertical lines
        horizontal_char - single character string used to draw horizontal lines
        horizontal_align_char - single character string used to indicate alignment
        junction_char - single character string used to draw line junctions
        junction_char - single character string used to draw line junctions
        top_junction_char - single character string used to draw top line junctions
        bottom_junction_char -
            single character string used to draw bottom line junctions
        right_junction_char - single character string used to draw right line junctions
        left_junction_char - single character string used to draw left line junctions
        top_right_junction_char -
            single character string used to draw top-right line junctions
        top_left_junction_char -
            single character string used to draw top-left line junctions
        bottom_right_junction_char -
            single character string used to draw bottom-right line junctions
        bottom_left_junction_char -
            single character string used to draw bottom-left line junctions
        sortby - name of field to sort rows by
        sort_key - sorting key function, applied to data points before sorting
        reversesort - True or False to sort in descending or ascending order
        print empty - if True, stringify just the header for an empty table,
            if False return an empty string"""
        ...

    def paginate(
        self, page_length: int = ..., line_break: str = ..., **kwargs
    ):  # -> str:
        ...
    def get_csv_string(self, **kwargs) -> str:
        """Return string representation of CSV formatted table in the current state

        Keyword arguments are first interpreted as table formatting options, and
        then any unused keyword arguments are passed to csv.writer(). For
        example, get_csv_string(header=False, delimiter='\t') would use
        header as a PrettyTable formatting option (skip the header row) and
        delimiter as a csv.writer keyword argument.
        """
        ...

    def get_json_string(self, **kwargs) -> str:
        """Return string representation of JSON formatted table in the current state

        Keyword arguments are first interpreted as table formatting options, and
        then any unused keyword arguments are passed to json.dumps(). For
        example, get_json_string(header=False, indent=2) would use header as
        a PrettyTable formatting option (skip the header row) and indent as a
        json.dumps keyword argument.
        """
        ...

    def get_html_string(self, **kwargs) -> str:
        """Return string representation of HTML formatted version of table in current
        state.

        Arguments:

        title - optional table title
        start - index of first data row to include in output
        end - index of last data row to include in output PLUS ONE (list slice style)
        fields - names of fields (columns) to include
        header - print a header showing field names (True or False)
        border - print a border around the table (True or False)
        preserve_internal_border - print a border inside the table even if
            border is disabled (True or False)
        hrules - controls printing of horizontal rules after rows.
            Allowed values: ALL, FRAME, HEADER, NONE
        vrules - controls printing of vertical rules between columns.
            Allowed values: FRAME, ALL, NONE
        int_format - controls formatting of integer data
        float_format - controls formatting of floating point data
        custom_format - controls formatting of any column using callable
        padding_width - number of spaces on either side of column data (only used if
            left and right paddings are None)
        left_padding_width - number of spaces on left hand side of column data
        right_padding_width - number of spaces on right hand side of column data
        sortby - name of field to sort rows by
        sort_key - sorting key function, applied to data points before sorting
        attributes - dictionary of name/value pairs to include as HTML attributes in the
            <table> tag
        format - Controls whether or not HTML tables are formatted to match
            styling options (True or False)
        xhtml - print <br/> tags if True, <br> tags if False"""
        ...

    def get_latex_string(self, **kwargs) -> str:
        """Return string representation of LaTex formatted version of table in current
        state.

        Arguments:

        start - index of first data row to include in output
        end - index of last data row to include in output PLUS ONE (list slice style)
        fields - names of fields (columns) to include
        header - print a header showing field names (True or False)
        border - print a border around the table (True or False)
        preserve_internal_border - print a border inside the table even if
            border is disabled (True or False)
        hrules - controls printing of horizontal rules after rows.
            Allowed values: ALL, FRAME, HEADER, NONE
        vrules - controls printing of vertical rules between columns.
            Allowed values: FRAME, ALL, NONE
        int_format - controls formatting of integer data
        float_format - controls formatting of floating point data
        sortby - name of field to sort rows by
        sort_key - sorting key function, applied to data points before sorting
        format - Controls whether or not HTML tables are formatted to match
            styling options (True or False)
        """
        ...

def from_csv(fp, field_names: Any | None = ..., **kwargs):  # -> PrettyTable:
    ...
def from_db_cursor(cursor, **kwargs):  # -> PrettyTable | None:
    ...
def from_json(json_string, **kwargs):  # -> PrettyTable:
    ...

class TableHandler(HTMLParser):
    def __init__(self, **kwargs) -> None: ...
    def handle_starttag(self, tag, attrs) -> None: ...
    def handle_endtag(self, tag) -> None: ...
    def handle_data(self, data) -> None: ...
    def generate_table(self, rows):  # -> PrettyTable:
        """
        Generates from a list of rows a PrettyTable object.
        """
        ...

    def make_fields_unique(self, fields) -> None:
        """
        iterates over the row and make each field unique
        """
        ...

def from_html(html_code, **kwargs):  # -> list[list[Any]]:
    """
    Generates a list of PrettyTables from a string of HTML code. Each <table> in
    the HTML becomes one PrettyTable object.
    """
    ...

def from_html_one(html_code, **kwargs):  # -> list[Any]:
    """
    Generates a PrettyTables from a string of HTML code which contains only a
    single <table>
    """
    ...
